version: 2
jobs:
  test-python:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              python3 -m venv env
              . env/bin/activate
              pip install -r requirements.txt
              # mkdir dvc-temp
              # dvc remote add -d ./dvc-temp
      # - run:
      #     name: Train
      #     command: |
      #         . env/bin/activate
      #         python validate.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-python