version: 2
jobs:
  test-python:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              python3 -m venv env
              . env/bin/activate
              pip install --upgrade pip
              pip install awscli
              aws configure set region us-east-2
              pip install -r requirements.txt
              dvc remote add s3 s3://gorcenski-test-dvc
      - run:
          name: Run tests
          command: |
              . env/bin/activate
              dvc pull -r s3
              pytest validate.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-python