version: 2
jobs:
  test-python:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              cd ./python && python3 -m venv env
              . env/bin/activate
              pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
              cd ./python && . env/bin/activate
              pytest safe_spaces_test.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-python